print("Hello python!")
print("以下是 python 的基本資料類型 (int, float, str, bool)")
print(15) #整數,(int)
print(15.0) #浮點數,(float)
print("15.0") #字串,(str)
print('15.0') #字串,(str)
print(True) #布林值,(bool)
print(False) #布林值,(bool)